### ISSUE TITLE
I suggest you use the secret feature in Github Action.

### ISSUE THREAD

**Issue by Fireblossom** [SuperRitchie/script-workflow#1]
Because the account and password are base64-encoded strings, they can be easily converted to plaintext.

**Comment by SuperRitchie** [comment]
Hey Fireblossom, thanks for pointing out my rookie mistake! I only had time to fix it just now by switching the credentials to repository secrets. 😅

The only issue I have now is that the commit history is still visible. Is there anyway to keep the code intact while deleting the commit history?

**Comment by SuperRitchie** [comment]
> Because the account and password are base64-encoded strings, they can be easily converted to plaintext.

Hey Fireblossom, thanks for pointing out my rookie mistake! I only had time to fix it just now by switching the credentials to repository secrets. 😅

The only issue I have now is that the commit history is still visible. Is there anyway to keep the code intact while deleting the commit history?

**Comment by Fireblossom** [comment]
Hi SuperRitchie!
I think you can either switch this repo to private or use BFG (see [this](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository) article) to clean your password in the commit history.

**Comment by SuperRitchie** [comment]
@Fireblossom 

Thanks for the BFG recommendation, it worked for me and I can keep the repository public now!
